#!/usr/bin/env bash
set -euo pipefail

# Runs Move unit tests with the package self-address rewritten to the deployed PACKAGE_ID.
# This does NOT hit the live chain; it recompiles the package so that the self-address
# (TokenBoilerplate) matches the published address, helping catch address-sensitive issues
# (e.g., cross-package references after publish).
#
# Source of PACKAGE_ID (in order):
#  1. Existing environment variable PACKAGE_ID
#  2. .env.local file (generated by publish_local.sh)
#  3. .last_publish_output.json (using jq)
#
# Usage (standalone):
#   bash scripts/move_test_deployed.sh
#
# Optional env vars:
#   PACKAGE_ID=<0x...>
#   ADMIN_ADDR=<0x...>   # If you want to also replace admin address placeholder (optional)
#   KEEP_TMP=1           # Do not delete the temp directory (for debugging)
#
# Result: runs `sui move test --path <temp_pkg>`

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)
PKG_SRC_DIR="$ROOT_DIR/packages/contracts"
MOVE_TOML="$PKG_SRC_DIR/Move.toml"

if [ ! -f "$MOVE_TOML" ]; then
  echo "[deploy-test] ERROR: Move.toml not found at $MOVE_TOML" >&2
  exit 1
fi

# 1. PACKAGE_ID resolution
if [ -z "${PACKAGE_ID:-}" ]; then
  if [ -f "$ROOT_DIR/.env.local" ]; then
    # shellcheck disable=SC1091
    source "$ROOT_DIR/.env.local" || true
  fi
fi
if [ -z "${PACKAGE_ID:-}" ] && command -v jq >/dev/null 2>&1 && [ -f "$ROOT_DIR/.last_publish_output.json" ]; then
  PACKAGE_ID=$(jq -r '.packageId // empty' "$ROOT_DIR/.last_publish_output.json" || true)
fi

if [ -z "${PACKAGE_ID:-}" ]; then
  echo "[deploy-test] ERROR: PACKAGE_ID not found. Publish first or export PACKAGE_ID." >&2
  exit 1
fi

if ! grep -qi "^[[]package[]]" "$MOVE_TOML" >/dev/null 2>&1; then
  echo "[deploy-test] WARNING: Move.toml doesn't look standard; continuing." >&2
fi

echo "[deploy-test] Using PACKAGE_ID=$PACKAGE_ID" >&2

TMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/move_pkg_deployed_XXXXXX")
cleanup() { if [ -z "${KEEP_TMP:-}" ]; then rm -rf "$TMP_DIR" || true; else echo "[deploy-test] Keeping temp dir $TMP_DIR" >&2; fi; }
trap cleanup EXIT

# Copy package (exclude build artifacts if any)
rsync -a --exclude build "$PKG_SRC_DIR/" "$TMP_DIR/"

PATCHED_TOML="$TMP_DIR/Move.toml"

# Replace any TokenBoilerplate assignment (in [addresses] or [dev-addresses]) with deployed PACKAGE_ID, preserving quotes.
# Previous version accidentally injected an unquoted numeric (hex) literal which broke TOML parsing.
perl -0777 -pe "s/^\s*TokenBoilerplate\s*=\s*\"[^\"]*\"/TokenBoilerplate =  \"$PACKAGE_ID\"/mg" "$PATCHED_TOML" > "$PATCHED_TOML.patched" && mv "$PATCHED_TOML.patched" "$PATCHED_TOML"

# Debug: print the rewritten TokenBoilerplate line
grep -i '^TokenBoilerplate' "$PATCHED_TOML" >&2 || echo "[deploy-test] WARNING: TokenBoilerplate line not found after rewrite" >&2

# Always unify admin address: prefer ADMIN_ADDR env, else keep existing (including '_' placeholder); if '_' present, set to a deterministic pseudo address for tests (derive from PACKAGE_ID tail)
ADMIN_ADDR_EFFECTIVE="${ADMIN_ADDR:-}"
if [ -z "$ADMIN_ADDR_EFFECTIVE" ]; then
  # Extract existing value
  EXISTING_ADMIN=$(grep -i '^admin' "$PATCHED_TOML" | head -n1 | sed -E 's/.*=\s*"([^"]*)".*/\1/' || true)
  if [ "$EXISTING_ADMIN" = "_" ]; then
    ADMIN_ADDR_EFFECTIVE="0x${PACKAGE_ID:2:8}deadbeef"
  else
    ADMIN_ADDR_EFFECTIVE="$EXISTING_ADMIN"
  fi
fi
perl -0777 -pe "s/^\s*admin\s*=\s*\"[^\"]*\"/admin =  \"$ADMIN_ADDR_EFFECTIVE\"/mg" "$PATCHED_TOML" > "$PATCHED_TOML.patched" && mv "$PATCHED_TOML.patched" "$PATCHED_TOML"
echo "[deploy-test] Using admin address $ADMIN_ADDR_EFFECTIVE" >&2

echo "[deploy-test] Rewritten Move.toml (TokenBoilerplate -> $PACKAGE_ID). Running tests..." >&2

# Run tests with force recompile to ensure new address mapping takes effect
sui move test --force --path "$TMP_DIR" "$@"
